name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g. 1.0.4)'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyside6

      - name: Get metadata
        id: meta
        run: |
          echo "ver=${{ github.event.inputs.version }}" >> $env:GITHUB_OUTPUT
          echo "tag=v${{ github.event.inputs.version }}" >> $env:GITHUB_OUTPUT

      - name: Build EXE
        run: |
          pyinstaller --clean --noupx --onedir --windowed --collect-all PySide6 `
            --name TaiAnhSieuToc `
            --icon .\app.ico `
            .\image_downloader_app.py

      - name: Create ZIP
        run: |
          Compress-Archive -Path "dist/TaiAnhSieuToc/*" -DestinationPath "dist/TaiAnhSieuToc_${{ steps.meta.outputs.ver }}.zip"

      - name: Create GitHub Release + upload ZIP
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          name: ${{ steps.meta.outputs.tag }}
          body: Release ${{ steps.meta.outputs.ver }}: build and auto-update package
          files: |
            dist/TaiAnhSieuToc_${{ steps.meta.outputs.ver }}.zip

      - name: Update manifest (version, url, sha256)
        shell: pwsh
        run: |
          $zipPath = "dist/TaiAnhSieuToc_${{ steps.meta.outputs.ver }}.zip"
          $sha256 = (Get-FileHash -Algorithm SHA256 $zipPath).Hash.ToLower()
          $manifestPath = "public/tai_anh_sieu_toc.json"

          $man = Get-Content -Raw -Encoding UTF8 $manifestPath | ConvertFrom-Json
          $man.version = "${{ steps.meta.outputs.ver }}"
          $man.windows.url = "https://github.com/${{ github.repository }}/releases/download/${{ steps.meta.outputs.tag }}/TaiAnhSieuToc_${{ steps.meta.outputs.ver }}.zip"
          $man.windows.sha256 = $sha256

          $man | ConvertTo-Json -Depth 3 | Set-Content -Encoding UTF8 $manifestPath

      - name: Commit and push manifest
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add public/tai_anh_sieu_toc.json
          git commit -m "chore: update manifest to ${{ steps.meta.outputs.ver }}"
          git push
